### ISSUE TITLE
Is it possible to use the module to "take a picture"

### ISSUE THREAD

**Issue by nitins1** [ktcy/CameraLayer#6]
I'm looking through CameraLayer.coffee and I see a capture function and it returns a path and a DOMstring. could I use that function to "take a picture"? Would I need to create a 'canvas' element or something like that?

**Comment by ktcy** [comment]
The most convenient way to take a picture is to use `capture()` method you mentioned. I didn't write it on README because I'm regarding it as experimental, but you can use it as follows.

```coffee
# Create and start CameraLayer.
camera = new CameraLayer()
camera.start()

# Create an empty layer to store an image to be captured by CameraLayer.
photo = new Layer()

# Take a picture.
photo.image = camera.capture()
```

Also, if you are familiar with HTML Canvas API, you can build your own capture method. CameraLayer is based on Framer's built-in VideoLayer, so you can access video stream via `player` property to draw it on a canvas element.

**Comment by ktcy** [comment]
This has been pushed to the repository and documented in README.
